openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
paths:
  /jobs/{jobId}:
    put:
      parameters:
        - in: path
          name: jobId
          description: A unique identifier for a job
          schema:
            $ref: "#/components/schemas/jobId"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Job title
                  example: My job
              required:
                - title
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    $ref: "#/components/schemas/jobId"
                  title:
                    type: string
                    description: Job title
                    example: My job
                required:
                  - jobId
                  - title
components:
  schemas:
    jobId:
      type: string
      description: A unique identifier for a job
      example: "12345"
