@baseUrl = http://localhost:3000

### POST
### signUp
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "test-user1",
  "email": "test-user@example.com",
  "password": "TestUser#1",
  "status": "FREE"
}

### POST signIn
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "test-user@example.com",
  "password": "TestUser#1"
}
