@baseUrl = http://localhost:3000

### GET
### FindAll
GET {{baseUrl}}/items

### FindById
@itemId = 297d825a-9863-4664-a4f0-0344fe4c704c
GET {{baseUrl}}/items/{{itemId}}


### POST create
// auth/signin APIでトークンを取得しておく

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NWFkMTkzZS0zZTdmLTQzOTAtYWM3Ni00ZmEyZGY5NGE5YWYiLCJ1c2VybmFtZSI6InRlc3QtdXNlcjEiLCJzdGF0dXMiOiJGUkVFIiwiaWF0IjoxNzQzNjAwNDkxLCJleHAiOjE3NDM2MDQwOTF9.ye4HjFjM11kQYT3fePhvYmHnHbJQbMGJ6bMEl8-a2SE
POST {{baseUrl}}/items
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "test2",
  "price": 456
}

### PUT
PUT {{baseUrl}}/items/{{itemId}}
Authorization: Bearer {{authToken}}

### DELETE
DELETE {{baseUrl}}/items/{{itemId}}
Authorization: Bearer {{authToken}}
