@baseUrl = http://localhost:3000

### GET
### FindAll
GET {{baseUrl}}/items

### FindById
@itemId = 4a4c7955-5f89-4f21-946e-c14e9ca45bc4
GET {{baseUrl}}/items/{{itemId}}


### POST create
// auth/signin APIでトークンを取得しておく

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NWFkMTkzZS0zZTdmLTQzOTAtYWM3Ni00ZmEyZGY5NGE5YWYiLCJ1c2VybmFtZSI6InRlc3QtdXNlcjEiLCJzdGF0dXMiOiJGUkVFIiwiaWF0IjoxNzQzNTk1NzAzLCJleHAiOjE3NDM1OTkzMDN9.DB17q6U-61MjIraEbl3rT61Dr8-Joj_Q2voNGsoqTIk
POST {{baseUrl}}/items
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "test2",
  "price": 456
}

### PUT
PUT {{baseUrl}}/items/{{itemId}}

### DELETE
DELETE {{baseUrl}}/items/{{itemId}}
